### ISSUE TITLE
Перетирает ctrl shift p

### ISSUE THREAD

**Issue by xahon** [ViktorQvarfordt/Sublime-Eval#1]
Отстой полный в стиле русского софта. Перетирает хоткей переключения проекта, нет меню настроек и хоткеев

**Comment by ViktorQvarfordt** [comment]
Thanks for your input. I agree regarding keybinds. I've just pushed a new version that removes default keybinds. The new version contains lots of improvements, see the readme. Check it out and let me know what you think.
